controllers/CarreraController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Carrera;
use app\models\CarreraSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii2mod\rbac\filters\AccessControl;

/**
 * CarreraController implements the CRUD actions for Carrera model.
 */
class CarreraController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'allowActions' => [
                    // 'index',
                    // // The actions listed here will be allowed to everyone including guests.
                ]
            ],
        ];
    }
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * Lists all Carrera models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CarreraSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Carrera model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Carrera model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Carrera();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idCarrera]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Carrera model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idCarrera]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Carrera model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Carrera model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Carrera the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Carrera::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/EventController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Event;
use app\models\EventSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii2mod\rbac\filters\AccessControl;
use yii\web\UploadedFile;
use app\models\UserEvent;
/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'allowActions' => [
                    // 'index',
                    // // The actions listed here will be allowed to everyone including guests.
                ]
            ],
        ];
    }
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        if(Yii::$app->user->can('Ver Todos') || (Yii::$app->user->can('Ver en Evento') && UserEvent::find()->where(['idUser'=>Yii::$app->user->id])->andWhere(['idEvent'=>$model->idEvent])->one())){
            return $this->render('view', [
                'model' => $model,
            ]);
        }else{
            return $this->redirect(['index']);
        }
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        // $model = new Event();
        // $model->break_quantity =0;
        // $model->banner = UploadedFile::getInstance($model, 'banner');
        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        //     return $this->redirect(['view', 'id' => $model->idEvent]);
        // }

        // return $this->render('create', [
        //     'model' => $model,
        // ]);

    $model = new Event();
    if ($model->load(Yii::$app->request->post())) {
        $model->banner = UploadedFile::getInstance($model, 'banner');

        if ($model->validate()) {
            if ($model->banner) {
                $filePath = 'uploads/' . $model->banner->baseName . '.' . $model->banner->extension;
                if ($model->banner->saveAs($filePath)) {
                    $model->banner_route = '/'.$filePath;
                }
            }

            if ($model->save(false)) {
                return $this->redirect(['view', 'id' => $model->idEvent]);
            }
        }
    }

    return $this->render('create', [
        'model' => $model,
    ]);

    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        // $model = $this->findModel($id);
        // $model->banner = UploadedFile::getInstance($model, 'banner');
        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        //     return $this->redirect(['view', 'id' => $model->idEvent]);
        // }

        // return $this->render('update', [
        //     'model' => $model,
        // ]);
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
        $model->banner = UploadedFile::getInstance($model, 'banner');

        if ($model->validate()) {
                if ($model->banner) {
                    $filePath = 'uploads/' . $model->banner->baseName . '.' . $model->banner->extension;
                    if ($model->banner->saveAs($filePath)) {
                        $model->banner_route = '/'.$filePath;
                    }
                }

                if ($model->save(false)) {
                    return $this->redirect(['view', 'id' => $model->idEvent]);
                }
            }
        }

        if(Yii::$app->user->can('Ver Todos') || (Yii::$app->user->can('Ver en Evento') && UserEvent::find()->where(['idUser'=>Yii::$app->user->id])->andWhere(['idEvent'=>$model->idEvent])->one())){
            return $this->render('update', [
                'model' => $model,
            ]);
        }else{
            return $this->redirect(['index']);
        }

        

    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii2mod\rbac\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'allowActions' => [
                    //'index',
                    // // The actions listed here will be allowed to everyone including guests.
                ]
            ],
        ];
    }
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->password_reset_token = Yii::$app->getSecurity()->generateRandomString();
        $model->authKey = Yii::$app->getSecurity()->generateRandomString();
        if ($model->load(Yii::$app->request->post())){
            $model->password = Yii::$app->getSecurity()->generatePasswordHash($model->password);
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);    
            }
            
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->password_reset_token = Yii::$app->getSecurity()->generateRandomString();
        //$model->authKey = Yii::$app->getSecurity()->generateRandomString();
        if ($model->load(Yii::$app->request->post())){
            $model->password = Yii::$app->getSecurity()->generatePasswordHash($model->password);
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);    
            }
            
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            //['label' => 'Home', 'url' => ['/site/index']],
            //['label' => 'About', 'url' => ['/site/about']],
            //['label' => 'Contact', 'url' => ['/site/contact']],
            //['label' => 'RBAC', 'url' => ['/rbac']],
            // ['label' => 'Users', 'items' => [
            //         ['label' => 'Index', 'url' => ['/user/index']],
            //         ['label' => 'Create', 'url' => ['/user/create']],
            //         ['label' => 'RBAC', 'items' => [
            //                 // ['label' => 'Index', 'url' => ['/rbac']],
            //                 ['label' => 'Route', 'url' => ['/rbac/route']],
            //                 ['label' => 'Permission', 'url' => ['/rbac/permission']],
            //                 ['label' => 'Role', 'url' => ['/rbac/role']],
            //                 ['label' => 'Assignment', 'url' => ['/rbac/assignment']],
            //             ],
            //         ],
            //     ],
            // ],
            //['label' => 'Events', 'url' => ['/event/index']],

            // Yii::$app->user->can('/event/create') || Yii::$app->user->can('/event/index') ? (
            //     ['label' => 'Events', 'items' => [
            //         ['label' => 'Index', 'url' => ['/event/index']],
            //         ['label' => 'Create', 'url' => ['/event/create']],
            //     ],
            // ]
            // ) :
            //['label' => 'Events', 'url' => ['/event/index'], Yii::$app->user->can('/event/index') ? (['visible' =>'true']) : (['visible' =>'false'])],
            // ['label' => 'RBAC', 'items' => 
            //     [
            //         ['label' => 'Route', 'url' => ['/rbac/route']],
            //         ['label' => 'Permission', 'url' => ['/rbac/permission']],
            //         ['label' => 'Role', 'url' => ['/rbac/role']],
            //         ['label' => 'Assignment', 'url' => ['/rbac/assignment']],
            //     ],
            // ],


            Yii::$app->user->can('/user/index') ? (
                ['label' => 'Usuarios', 'url' => ['/user/index'],'visible' =>true]
            ) : (
                ['label' => 'Usuarios', 'url' => ['/user/index'],'visible' =>false]
            ),

            Yii::$app->user->can('/rbac/route/index') || Yii::$app->user->can('/rbac/permission/index') || Yii::$app->user->can('/rbac/role/index') || Yii::$app->user->can('/rbac/assignment/index') ? (
                ['label' => 'RBAC', 'items' => 
                    [
                        Yii::$app->user->can('/rbac/route/index') ? (
                            ['label' => 'Rutas', 'url' => ['/rbac/route/index'],'visible' =>true]
                        ) : (
                            ['label' => 'Rutas', 'url' => ['/rbac/route/index'],'visible' =>false]
                        ),
                        Yii::$app->user->can('/rbac/permission/index') ? (
                            ['label' => 'Permisos', 'url' => ['/rbac/permission/index'],'visible' =>true]
                        ) : (
                            ['label' => 'Permisos', 'url' => ['/rbac/permission/index'],'visible' =>false]
                        ),
                        Yii::$app->user->can('/rbac/role/index') ? (
                            ['label' => 'Roles', 'url' => ['/rbac/role/index'],'visible' =>true]
                        ) : (
                            ['label' => 'Roles', 'url' => ['/rbac/role/index'],'visible' =>false]
                        ),
                        Yii::$app->user->can('/rbac/assignment/index') ? (
                            ['label' => 'Asignacion', 'url' => ['/rbac/assignment/index'],'visible' =>true]
                        ) : (
                            ['label' => 'Asignacion', 'url' => ['/rbac/assignment/index'],'visible' =>false]
                        ),
                    ],
                ]
            ) : (
                ['label' => 'RBAC', 'url' => ['/rbac'],'visible' =>false]
            ),

            Yii::$app->user->can('/carrera/index') ? (
                ['label' => 'Carreras', 'url' => ['/carrera/index'],'visible' =>true]
            ) : (
                ['label' => 'Carreras', 'url' => ['/carrera/index'],'visible' =>false]
            ),

            Yii::$app->user->can('/event/index') ? (
                ['label' => 'Eventos', 'url' => ['/event/index'],'visible' =>true]
            ) : (
                ['label' => 'Eventos', 'url' => ['/event/index'],'visible' =>false]
            ),

            
            Yii::$app->user->can('/user-event/index') ? (
                ['label' => 'Usuarios - Evento', 'url' => ['/user-event/index'],'visible' =>true]
            ) : (
                ['label' => 'Usuarios - Evento', 'url' => ['/user-event/index'],'visible' =>false]
            ),

            Yii::$app->user->can('/conference/index') ? (
                ['label' => 'Conferencias', 'url' => ['/conference/index'],'visible' =>true]
            ) : (
                ['label' => 'Conferencias', 'url' => ['/conference/index'],'visible' =>false]
            ),

            Yii::$app->user->can('/attendant/index') ? (
                ['label' => 'Personas', 'url' => ['/attendant/index'],'visible' =>true]
            ) : (
                ['label' => 'Personas', 'url' => ['/attendant/index'],'visible' =>false]
            ),

            Yii::$app->user->can('/event-registration/index') ? (
                ['label' => 'Registro a Eventos', 'url' => ['/event-registration/index'],'visible' =>true]
            ) : (
                ['label' => 'Registro a Eventos', 'url' => ['/event-registration/index'],'visible' =>false]
            ),

            Yii::$app->user->can('/attendance-record-conference/index') ? (
                ['label' => 'Asistencia', 'url' => ['/attendance-record-conference/index'],'visible' =>true]
            ) : (
                ['label' => 'Asistencia', 'url' => ['/attendance-record-conference/index'],'visible' =>false]
            ),

            Yii::$app->user->can('/event-registration/break') ? (
                ['label' => 'Breaks', 'url' => ['/event-registration/break'],'visible' =>true]
            ) : (
                ['label' => 'Breaks', 'url' => ['/event-registration/break'],'visible' =>false]
            ),


            // Yii::$app->user->can('/translatemanager/language/list') ? (
            //     ['label' => 'Language', 
            //         'items' => [
            //             ['label' => 'List', 'url' => ['/translatemanager/language/list']],
            //             ['label' => 'Create', 'url' => ['/translatemanager/language/create']],
            //             ['label' => 'Scan', 'url' => ['/translatemanager/language/scan']],
            //             ['label' => 'Optimizer', 'url' => ['/translatemanager/language/optimizer']],
            //         ],     
            //     ]
            // ) :

            //['label' => 'Carrers', 'url' => ['/carrera/index']],
            // ['label' => 'Carrers', 'items' => [
            //         ['label' => 'Index', 'url' => ['/carrera/index']],
            //         ['label' => 'Create', 'url' => ['/carrera/create']],
            //     ],
            // ],
            //['label' => 'Conference', 'url' => ['/conference/index']],
            // ['label' => 'Conference', 'items' => [
            //         ['label' => 'Index', 'url' => ['/conference/index']],
            //         ['label' => 'Create', 'url' => ['/conference/create']],
            //     ],
            // ],
            //['label' => 'Attendants', 'url' => ['/attendant/index']],
            // ['label' => 'Attendants', 'items' => [
            //         ['label' => 'Index', 'url' => ['/attendant/index']],
            //         ['label' => 'Create', 'url' => ['/attendant/create']],
            //     ],
            // ],
            //['label' => 'Event - Users', 'url' => ['/user-event/index']],
            // ['label' => 'Event - Users', 'items' => [
            //         ['label' => 'Index', 'url' => ['/user-event/index']],
            //         ['label' => 'Create', 'url' => ['/user-event/create']],
            //     ],
            // ],
            //['label' => 'Event Registration', 'url' => ['/event-registration/index']],
            // ['label' => 'Registration', 'items' => [
            //         ['label' => 'Index', 'url' => ['/event-registration/index']],
            //         ['label' => 'Create', 'url' => ['/event-registration/create']],
            //         ['label' => 'Breaks', 'url' => ['/event-registration/break']],
            //     ],
            // ],
            //['label' => 'Attendance', 'url' => ['/attendance-record-conference/index']],
            // ['label' => 'Attendance', 'items' => [
            //         ['label' => 'Index', 'url' => ['/attendance-record-conference/index']],
            //         ['label' => 'Create', 'url' => ['/attendance-record-conference/create']],
            //     ],
            // ],
            // ['label' => 'Breaks', 'url' => ['/event-registration/break']],
            // ['label' => 'Language', 
            //     'items' => [
            //         ['label' => 'List', 'url' => ['/translatemanager/language/list']],
            //         ['label' => 'Create', 'url' => ['/translatemanager/language/create']],
            //         ['label' => 'Scan', 'url' => ['/translatemanager/language/scan']],
            //         ['label' => 'Optimizer', 'url' => ['/translatemanager/language/optimizer']],
            //     ],     
            // ],
            //['label' => 'Language', 'url' => ['/translatemanager/language/list']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-right">&copy; UDLA <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>