models/AttendanceRecordConference.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "attendance_record_conference".
 *
 * @property int $idAttendant
 * @property int $idConference
 * @property string $registration_date
 * @property int $idUser
 *
 * @property Event $event
 * @property Attendant $attendant
 * @property Conference $conference
 * @property User $user
 */
class AttendanceRecordConference extends \yii\db\ActiveRecord
{
    public $event_name;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'attendance_record_conference';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['idAttendant', 'idConference', 'registration_date', 'idUser'], 'required'],
            [['idAttendant', 'idConference', 'idUser'], 'integer'],
            [['event_name'], 'string'],
            [['registration_date','event_name'], 'safe'],
            [['idAttendant', 'idConference'], 'unique', 'targetAttribute' => ['idAttendant', 'idConference']],
            [['idAttendant'], 'exist', 'skipOnError' => true, 'targetClass' => Attendant::className(), 'targetAttribute' => ['idAttendant' => 'idAttendant']],
            [['idConference'], 'exist', 'skipOnError' => true, 'targetClass' => Conference::className(), 'targetAttribute' => ['idConference' => 'idConference']],
            [['idUser'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['idUser' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'idAttendant' => 'Id Attendant',
            'idConference' => 'Id Conference',
            'registration_date' => 'Fecha de Registro',
            'idUser' => 'Id User',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAttendant()
    {
        return $this->hasOne(Attendant::className(), ['idAttendant' => 'idAttendant']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConference()
    {
        return $this->hasOne(Conference::className(), ['idConference' => 'idConference']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'idUser']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(Event::className(), ['idEvent' => 'idEvent'])->viaTable('conference', ['idConference' => 'idConference']);
    }

    public function getDetails(){
        return $this->conference->conference_name+' - '+$this->registration_date;
    }

}

controllers/AttendanceRecordConferenceController.php
<?php

namespace app\controllers;

use Yii;
use app\models\AttendanceRecordConference;
use app\models\AttendanceRecordConferenceSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii2mod\rbac\filters\AccessControl;
use app\models\Conference;
use app\models\EventRegistration;
use app\models\UserEvent;

/**
 * AttendanceRecordConferenceController implements the CRUD actions for AttendanceRecordConference model.
 */
class AttendanceRecordConferenceController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'allowActions' => [
                    // 'index',
                    // // The actions listed here will be allowed to everyone including guests.
                ]
            ],
        ];
    }

    // public function behaviors()
    // {
    //     return [
    //         'access' => [
    //             'class' => AccessControl::class,
    //             'rules' => [
    //                 [
    //                     'allow' => true,
    //                     'actions' => ['index'],
    //                     'roles' => ['/attendance-record-conference/*'],
    //                 ],
    //                 [
    //                     'allow' => true,
    //                     'actions' => ['view'],
    //                     'roles' => ['viewARC'],
    //                 ],
    //                 [
    //                     'allow' => true,
    //                     'actions' => ['create'],
    //                     'roles' => ['createARC'],
    //                 ],
    //                 [
    //                     'allow' => true,
    //                     'actions' => ['update'],
    //                     'roles' => ['updateARC'],
    //                 ],
    //                 [
    //                     'allow' => true,
    //                     'actions' => ['delete'],
    //                     'roles' => ['deleteARC'],
    //                 ],
    //             ],
    //         ],
    //     ];
    // }
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * Lists all AttendanceRecordConference models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AttendanceRecordConferenceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AttendanceRecordConference model.
     * @param integer $idAttendant
     * @param integer $idConference
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($idAttendant, $idConference)
    {
        $model = $this->findModel($idAttendant, $idConference);
        if((UserEvent::find()->where(['idUser'=>Yii::$app->user->id])->andWhere(['idEvent'=>$model->event->idEvent])->one() && Yii::$app->user->can('Ver en Evento'))|| Yii::$app->user->can('Ver Todos')){  
            return $this->render('view', [
                'model' => $model,
            ]);
        }else{
            return $this->redirect(['index']);
        }
        
    }

    /**
     * Creates a new AttendanceRecordConference model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AttendanceRecordConference();
        $model->idUser = Yii::$app->user->id;
        $model->registration_date = date('Y-m-d h:i:s');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idAttendant' => $model->idAttendant, 'idConference' => $model->idConference]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing AttendanceRecordConference model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $idAttendant
     * @param integer $idConference
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($idAttendant, $idConference)
    {
        $model = $this->findModel($idAttendant, $idConference);
        $model->idUser = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idAttendant' => $model->idAttendant, 'idConference' => $model->idConference]);
        }

        if((UserEvent::find()->where(['idUser'=>Yii::$app->user->id])->andWhere(['idEvent'=>$model->event->idEvent])->one() && Yii::$app->user->can('Ver en Evento'))|| Yii::$app->user->can('Ver Todos')){  
            return $this->render('update', [
                'model' => $model,
            ]);
        }else{
            return $this->redirect(['index']);
        }

        
    }

    /**
     * Deletes an existing AttendanceRecordConference model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $idAttendant
     * @param integer $idConference
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($idAttendant, $idConference)
    {
        $this->findModel($idAttendant, $idConference)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AttendanceRecordConference model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $idAttendant
     * @param integer $idConference
     * @return AttendanceRecordConference the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($idAttendant, $idConference)
    {
        if (($model = AttendanceRecordConference::findOne(['idAttendant' => $idAttendant, 'idConference' => $idConference])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionConference() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $idEvent = end($_POST['depdrop_parents']);
            $list = Conference::find()->andWhere(['idEvent' => $idEvent])->asArray()->all();
            $selected  = null;
            if ($idEvent != null && count($list) > 0) {
                $selected = '';
                foreach ($list as $i => $conference) {
                    $out[] = ['id' => $conference['idConference'], 'name' => $conference['conference_name']];
                }

                echo Json::encode(['output' => $out, 'selected'=>$selected]);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected'=>'']);
    }

    public function actionAttendants() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $idEvent = end($_POST['depdrop_parents']);
            $list = EventRegistration::find()->andWhere(['idEvent' => $idEvent])->asArray()->all();
            $selected  = null;
            if ($idEvent != null && count($list) > 0) {
                $selected = '';
                foreach ($list as $i => $attedant) {
                    $out[] = ['id' => $attedant['idAttendant'], 'name' => $attedant['barcode']];
                }

                echo Json::encode(['output' => $out, 'selected'=>$selected]);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected'=>'']);
    }
}

views/attendance-record-conference/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\models\Conference;
use app\models\EventRegistration;
use app\models\Event;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\AttendanceRecordConference */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="attendance-record-conference-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php
    $time = new \DateTime('now');
    $today = $time->format('Y-m-d h:i:s');
    $events=Event::find()->joinWith(["userEvents eu"],true,"INNER JOIN")->where(['<=', 'start_date', $today])->andWhere(['>=', 'end_date', $today])->andWhere(["eu.idUser"=>Yii::$app->user->id])->all();

    $listData=ArrayHelper::map($events,'idEvent','event_name');


     echo $form->field($model, 'event')->dropDownList($listData, ['id'=>'idEvent'])->label('Event');

    ?>

    <?php
     echo $form->field($model, 'idConference')->widget(DepDrop::classname(), [
        'type'=>DepDrop::TYPE_SELECT2,
        'options'=>['id'=>'idConference', 'class'=>'form-control'],
        //'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
        'pluginOptions'=>[
            'depends'=>['idEvent'],
            'placeholder'=>'Select a Conference',
            'url'=>Url::to(['/attendance-record-conference/conference']),
        'initialize'=>true,
    ]])->label('Conference');
    ?>

    <?php
     echo $form->field($model, 'idAttendant')->widget(DepDrop::classname(), [
        'type'=>DepDrop::TYPE_SELECT2,
        'options'=>['id'=>'idAttendant', 'class'=>'form-control'],
        //'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
        'pluginOptions'=>[
            'depends'=>['idEvent'],
            'placeholder'=>'Select an Attendant',
            'url'=>Url::to(['/attendance-record-conference/attendants']),
        'initialize'=>true,
    ]])->label('Attendant');
    ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/attendance-record-conference/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AttendanceRecordConferenceSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="attendance-record-conference-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'idAttendant') ?>

    <?= $form->field($model, 'idConference') ?>

    <?= $form->field($model, 'registration_date') ?>

    <?= $form->field($model, 'idUser') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/attendance-record-conference/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\AttendanceRecordConference */

$this->title = 'Create Attendance Record Conference';
$this->params['breadcrumbs'][] = ['label' => 'Attendance Record Conferences', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="attendance-record-conference-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/attendance-record-conference/index.php
<?php

use yii\helpers\Html;
//use yii\grid\GridView;
use kartik\grid\GridView;
use kartik\export\ExportMenu;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AttendanceRecordConferenceSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Asistencia';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="attendance-record-conference-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Crear Asistencia', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= 
    Yii::$app->user->can('Generar Reportes') ? (
    ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'noExportColumns' => [],
        'filename' => 'Asistencia',
        'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                // 'idAttendant',
                [
                 'attribute' => 'event_name',
                 'label' => 'Evento',
                 'value' => 'event.event_name',
                 'visible'=> Yii::$app->user->can('Ver en Evento') || Yii::$app->user->can('Ver Todos'),
                 ],
                [
                 'attribute' => 'attendant',
                 'label' => 'Pasaporte',
                 'value' => 'attendant.passport'
                 ],
                 'attendant.first_name',
                 'attendant.last_name',
                // 'idConference',
                [
                 'attribute' => 'conference',
                 'label' => 'Conferencia',
                 'value' => 'conference.conference_name'
                 ],
                 
                'registration_date',
                // 'idUser',
                [
                 'attribute' => 'user',
                 'value' => 'user.username',
                 'label' => 'Usuario',
                 'visible'=> Yii::$app->user->can('Ver en Evento') || Yii::$app->user->can('Ver Todos'),
                 //'visible'=> ,
                 ],
                 
                ['class' => 'yii\grid\ActionColumn'],
            ],
        ])
    ) : (
        ''
        )
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'idAttendant',
            [
             'attribute' => 'event_name',
             'label' => 'Evento',
             'value' => 'event.event_name',
             'visible'=> Yii::$app->user->can('Ver en Evento') || Yii::$app->user->can('Ver Todos'),
             ],
            [
             'attribute' => 'attendant',
             'label' => 'Pasaporte',
             'value' => 'attendant.passport'
             ],

            // 'idConference',
            [
             'attribute' => 'conference',
             'label' => 'Conferencia',
             'value' => 'conference.conference_name'
             ],
             
            'registration_date',
            // 'idUser',
            [
             'attribute' => 'user',
             'value' => 'user.username',
             'label' => 'Usuario',
             'visible'=> Yii::$app->user->can('Ver en Evento') || Yii::$app->user->can('Ver Todos'),
             //'visible'=> ,
             ],
             
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/attendance-record-conference/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\AttendanceRecordConference */

$this->title = 'Update Attendance Record Conference: ' . $model->idAttendant;
$this->params['breadcrumbs'][] = ['label' => 'Attendance Record Conferences', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->idAttendant, 'url' => ['view', 'idAttendant' => $model->idAttendant, 'idConference' => $model->idConference]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="attendance-record-conference-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/attendance-record-conference/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\AttendanceRecordConference */

$this->title = $model->idAttendant;
$this->params['breadcrumbs'][] = ['label' => 'Attendance Record Conferences', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="attendance-record-conference-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'idAttendant' => $model->idAttendant, 'idConference' => $model->idConference], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Borrar', ['delete', 'idAttendant' => $model->idAttendant, 'idConference' => $model->idConference], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Seguro?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'attendant.first_name',
            'attendant.last_name',
            'attendant.passport',
            'conference.conference_name',
            'registration_date',
            'user.username',
            'event.event_name'
        ],
    ]) ?>

</div>