models/EventRegistration.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "event_registration".
 *
 * @property int $idAttendant
 * @property int $idEvent
 * @property string $registration_date
 * @property int $idUser
 * @property int $barcode
 * @property int $material
 * @property int $break_number
 *
 * @property Attendant $attendant
 * @property Event $event
 * @property User $user
 */
class EventRegistration extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'event_registration';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['idAttendant', 'idEvent', 'registration_date', 'idUser', 'barcode', 'material'], 'required'],
            [['idAttendant', 'idEvent', 'idUser', 'barcode', 'material', 'break_number'], 'integer'],
            [['registration_date'], 'safe'],
            [['idAttendant', 'idEvent'], 'unique', 'targetAttribute' => ['idAttendant', 'idEvent']],
            [['idEvent','barcode'], 'unique','targetAttribute' => ['idEvent','barcode']],
            [['idAttendant'], 'exist', 'skipOnError' => true, 'targetClass' => Attendant::className(), 'targetAttribute' => ['idAttendant' => 'idAttendant']],
            [['idEvent'], 'exist', 'skipOnError' => true, 'targetClass' => Event::className(), 'targetAttribute' => ['idEvent' => 'idEvent']],
            [['idUser'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['idUser' => 'id']],
            //[['break_number'], 'validateNumber'],
            [['break_number'], 'validateNumber', 'when' => function ($model) {
                return $model->event->breaks === 1;
            }],
            [['break_number'], 'validateBreak','params'=>['event'=>'event'], 'when' => function ($model) {
                return $model->event->breaks === 0;
            }],
        ];
    }

    public function validateNumber($attribute, $params, $validator)
    {
        if ($this->$attribute > $this->event->break_quantity) {
            $this->addError($attribute, 'Numero de breaks maximo alcanzado');
        }
    }

    public function validateBreak($attribute, $params, $validator)
    {
        if ($this->$attribute > 0) {
            $this->addError($attribute, 'No se habilitaron breaks para este evento');
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'idAttendant' => 'Id Attendant',
            'idEvent' => 'Id Event',
            'registration_date' => 'Fecha Registro',
            'idUser' => 'Id User',
            'barcode' => 'Código',
            'material' => 'Material',
            'break_number' => 'Número Break',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAttendant()
    {
        return $this->hasOne(Attendant::className(), ['idAttendant' => 'idAttendant']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(Event::className(), ['idEvent' => 'idEvent']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'idUser']);
    }

}

controllers/EventRegistrationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\EventRegistration;
use app\models\EventRegistrationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii2mod\rbac\filters\AccessControl;
use app\models\UserEvent;
/**
 * EventRegistrationController implements the CRUD actions for EventRegistration model.
 */
class EventRegistrationController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'allowActions' => [
                    // 'index',
                    // // The actions listed here will be allowed to everyone including guests.
                ]
            ],
        ];
    }
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['POST'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * Lists all EventRegistration models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EventRegistrationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single EventRegistration model.
     * @param integer $idAttendant
     * @param integer $idEvent
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($idAttendant, $idEvent)
    {
        $model = $this->findModel($idAttendant, $idEvent);
        if(Yii::$app->user->can('Ver Todos') || (Yii::$app->user->can('Ver en Evento') && UserEvent::find()->where(['idUser'=>Yii::$app->user->id])->andWhere(['idEvent'=>$model->event->idEvent])->one())){
            return $this->render('view', [
                'model' => $model,
            ]);
        }else{
            return $this->redirect(['index']);
        }
        
    }

    /**
     * Creates a new EventRegistration model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new EventRegistration();
        $model->idUser = Yii::$app->user->id;
        $model->registration_date = date('Y-m-d h:i:s');
        $model->break_number = 0;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idAttendant' => $model->idAttendant, 'idEvent' => $model->idEvent]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing EventRegistration model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $idAttendant
     * @param integer $idEvent
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($idAttendant, $idEvent)
    {
        $model = $this->findModel($idAttendant, $idEvent);
        $model->idUser = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idAttendant' => $model->idAttendant, 'idEvent' => $model->idEvent]);
        }

        //$model = $this->findModel($idAttendant, $idEvent);
        if(Yii::$app->user->can('Ver Todos') || (Yii::$app->user->can('Ver en Evento') && UserEvent::find()->where(['idUser'=>Yii::$app->user->id])->andWhere(['idEvent'=>$model->event->idEvent])->one())){
            return $this->render('update', [
            'model' => $model,
            ]);
        }else{
            return $this->redirect(['index']);
        }

        
    }

    /**
     * Deletes an existing EventRegistration model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $idAttendant
     * @param integer $idEvent
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($idAttendant, $idEvent)
    {
        $this->findModel($idAttendant, $idEvent)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the EventRegistration model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $idAttendant
     * @param integer $idEvent
     * @return EventRegistration the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($idAttendant, $idEvent)
    {
        if (($model = EventRegistration::findOne(['idAttendant' => $idAttendant, 'idEvent' => $idEvent])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionBreak()
    {
        $model = new EventRegistration();
        //$model = new EventRegistration(['scenario' => 'break']);


        if ($model->load(Yii::$app->request->post())) {
            $model = $this->findModel($model->idAttendant, $model->idEvent);
            $model->break_number++;
            if ($model->validate()) {
                $model->update();
                return $this->redirect(['break']);
            }
          
            
        }

        return $this->render('break', [
            'model' => $model,
        ]);
    }

    public function actionSample() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $idEvent = end($_POST['depdrop_parents']);
            $list = EventRegistration::find()->andWhere(['idEvent' => $idEvent])->asArray()->all();
            $selected  = null;
            if ($idEvent != null && count($list) > 0) {
                $selected = '';
                foreach ($list as $i => $registration) {
                    $out[] = ['id' => $registration['idAttendant'], 'name' => $registration['barcode']];
                }

                echo Json::encode(['output' => $out, 'selected'=>$selected]);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected'=>'']);
    }

}

views/event-registration/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\models\Event;
use app\models\Attendant;

/* @var $this yii\web\View */
/* @var $model app\models\EventRegistration */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-registration-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php
    $attendats=Attendant::find()->all();

    $data=ArrayHelper::map($attendats,'idAttendant','passport');

    echo $form->field($model, 'idAttendant')->widget(Select2::classname(), 
    [
        'data' => $data,
        'options' => ['placeholder' => 'Select an Attendant'],
        'pluginOptions' => [
        'allowClear' => true
     ],])->label('Attendant');

        ?>

    <?php
    $time = new \DateTime('now');
    $today = $time->format('Y-m-d h:i:s');
    $id = Yii::$app->user->id;
    $events=Event::find()->joinWith('userEvents')->where(['idUser'=>$id])->andWhere(['>=','end_date',$today])->andWhere(['<','start_date',$today])->all();

    $data=ArrayHelper::map($events,'idEvent','event_name');

    echo $form->field($model, 'idEvent')->widget(Select2::classname(), 
    [
        'data' => $data,
        'options' => ['placeholder' => 'Select an Event'],
        'pluginOptions' => [
        'allowClear' => true
     ],])->label('Event');

        ?>

    <?= $form->field($model, 'barcode')->textInput() ?>

    <?= $form->field($model, 'material')->checkBox() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/event-registration/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EventRegistrationSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-registration-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'idAttendant') ?>

    <?= $form->field($model, 'idEvent') ?>

    <?= $form->field($model, 'registration_date') ?>

    <?= $form->field($model, 'idUser') ?>

    <?= $form->field($model, 'barcode') ?>

    <?php // echo $form->field($model, 'material') ?>

    <?php // echo $form->field($model, 'break_number') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/event-registration/break.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\models\EventRegistration;
use app\models\Event;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\EventRegistration */
/* @var $form ActiveForm */
?>
<div class="event-registration-break">

    <?php $form = ActiveForm::begin(); ?>

    <?php
    $time = new \DateTime('now');
    $today = $time->format('Y-m-d h:i:s');
    $events=Event::find()->joinWith(["userEvents eu"],true,"INNER JOIN")->where(['<=', 'start_date', $today])->andWhere(['>=', 'end_date', $today])->andWhere(['=', 'breaks','1'])->andWhere(["eu.idUser"=>Yii::$app->user->id])->all();

    $listData=ArrayHelper::map($events,'idEvent','event_name');


     echo $form->field($model, 'idEvent')->dropDownList($listData, ['id'=>'idEvent'])->label('Event');

    ?>

    <?php
     echo $form->field($model, 'idAttendant')->widget(DepDrop::classname(), [
        'type'=>DepDrop::TYPE_SELECT2,
        'options'=>['id'=>'idAttendant', 'class'=>'form-control'],
        //'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
        'pluginOptions'=>[
            'depends'=>['idEvent'],
            'placeholder'=>'Select an Attendant',
            'url'=>Url::to(['/event-registration/sample']),
        'initialize'=>true,
    ]])->label('Attendant');
    ?>

    <?php
        echo $form->errorSummary($model,['header'=>'Error:'])

    ?>

    
        <div class="form-group">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- event-registration-break -->

views/event-registration/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\EventRegistration */

$this->title = 'Create Event Registration';
$this->params['breadcrumbs'][] = ['label' => 'Event Registrations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-registration-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/event-registration/index.php
<?php

use yii\helpers\Html;
//use yii\grid\GridView;
use kartik\grid\GridView;
use kartik\export\ExportMenu;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EventRegistrationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Registro a Eventos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-registration-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Crear Registro a Evento', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= 
    Yii::$app->user->can('Generar Reportes') ? (
    ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'noExportColumns' => [],
        'filename' => 'RegistroEventos',
        'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'attendant.first_name',
                'attendant.last_name',
                'attendant.passport',
                'event.event_name',
                'registration_date',
                'barcode',
                [
                 'attribute' => 'material',
                 'value' => function($model){return $model->material;},
                 'format' => 'boolean',
                 'visible' => function($model){return $model->event->material;},
                 ],
                [
                 'attribute' => 'break_number',
                 'value' => function($model){return $model->break_number;},
                 'visible' => function($model){return $model->event->breaks;},
                 ],
                 [
                    'attribute' => 'Total Attended Conferences',
                    'value' => function($model){return count($model->attendant->conferences);},
                 ],
                 [
                    'attribute' => 'Attended Conferences',
                    'value' => function($model){return implode(', ',\yii\helpers\ArrayHelper::map($model->attendant->conferences, 'idConference', 'conference_name'));},
                 ],

                    ['class' => 'yii\grid\ActionColumn'],
                ],
        ])
    ) : (
        ''
        )
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
             'attribute' => 'attendant',
             'label'=>'Pasaporte',
             'value' => 'attendant.passport'
             ],
            [
             'attribute' => 'event',
             'label'=>'Evento',
             'value' => 'event.event_name'
             ],
            'registration_date',
            [
             'attribute' => 'user',
             'value' => 'user.username',
             'label'=>'Usuario',
             'visible' =>Yii::$app->user->can('Ver en Evento') || Yii::$app->user->can('Ver Todos'),
             ],
            'barcode',
            Yii::$app->user->can('Generar Reportes') ? (
                [
                    'attribute'=>'material',
                    'format' =>'boolean',
                    'visible' =>'true',
                ]
            ) : (
                [
                    'attribute'=>'material',
                    'format' =>'boolean',
                    'visible' =>false,
                ]
        ),
            //'break_number',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/event-registration/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\EventRegistration */

$this->title = 'Update Event Registration: ' . $model->idAttendant;
$this->params['breadcrumbs'][] = ['label' => 'Event Registrations', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->idAttendant, 'url' => ['view', 'idAttendant' => $model->idAttendant, 'idEvent' => $model->idEvent]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="event-registration-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/event-registration/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\EventRegistration */

$this->title = $model->idAttendant;
$this->params['breadcrumbs'][] = ['label' => 'Event Registrations', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-registration-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'idAttendant' => $model->idAttendant, 'idEvent' => $model->idEvent], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'idAttendant' => $model->idAttendant, 'idEvent' => $model->idEvent], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Seguró?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'attendant.first_name',
            'attendant.last_name',
            'attendant.passport',
            'event.event_name',
            'registration_date',
            'user.username',
            'barcode',
            //'material:boolean',
            [
             'attribute' => 'material',
             'value' => $model->material,
             'format' => 'boolean',
             'visible' => $model->event->material,
             ],
            [
             'attribute' => 'break_number',
             'value' => $model->break_number,
             'visible' => $model->event->breaks,
             ],
            [
             'attribute' => 'Break Total',
             'value' => $model->event->break_quantity,
             'visible' => $model->event->breaks,
             ],
             [
                'attribute' => 'Total Attended Conferences',
                'value' => count($model->attendant->conferences),
             ],
             [
                'attribute' => 'Attended Conferences',
                'value' => implode(', ',\yii\helpers\ArrayHelper::map($model->attendant->conferences, 'idConference', 'conference_name')),
                'visible' => count($model->attendant->conferences)>0,
             ],

        ],
    ]) ?>

</div>